monolog:
    handlers:
        main:
            type: stream
            path: php://stderr
            level: debug
            channels: ['!event']
        # Disabled for now see - https://github.com/symfony/symfony/pull/46475
        #firephp:
        #    type: firephp
        #    level: info
        chromephp:
            type: chromephp
            level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
